-- MySQL Script generated by MySQL Workbench
-- Sun Sep  3 20:05:44 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema desafio_oficina
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `desafio_oficina` ;

-- -----------------------------------------------------
-- Schema desafio_oficina
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `desafio_oficina` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `desafio_oficina` ;

-- -----------------------------------------------------
-- Table `desafio_oficina`.`oficina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `desafio_oficina`.`oficina` ;

CREATE TABLE IF NOT EXISTS `desafio_oficina`.`oficina` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `cnpj` CHAR(14) NOT NULL,
  `endereco` VARCHAR(255) NOT NULL,
  `telefone` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `desafio_oficina`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `desafio_oficina`.`cliente` ;

CREATE TABLE IF NOT EXISTS `desafio_oficina`.`cliente` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `oficina_ID` INT NOT NULL,
  `cpf` CHAR(11) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Fone` VARCHAR(15) NOT NULL,
  `Endereco` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`, `oficina_ID`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  INDEX `fk_cliente_oficina1_idx` (`oficina_ID` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_oficina1`
    FOREIGN KEY (`oficina_ID`)
    REFERENCES `desafio_oficina`.`oficina` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `desafio_oficina`.`agendamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `desafio_oficina`.`agendamento` ;

CREATE TABLE IF NOT EXISTS `desafio_oficina`.`agendamento` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Descricao` VARCHAR(45) NOT NULL,
  `data` TIMESTAMP NOT NULL,
  `cliente_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `cliente_ID`),
  INDEX `fk_agendamento_cliente1_idx` (`cliente_ID` ASC) VISIBLE,
  CONSTRAINT `fk_agendamento_cliente1`
    FOREIGN KEY (`cliente_ID`)
    REFERENCES `desafio_oficina`.`cliente` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `desafio_oficina`.`equipe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `desafio_oficina`.`equipe` ;

CREATE TABLE IF NOT EXISTS `desafio_oficina`.`equipe` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `desafio_oficina`.`veiculo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `desafio_oficina`.`veiculo` ;

CREATE TABLE IF NOT EXISTS `desafio_oficina`.`veiculo` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Placa` VARCHAR(12) NOT NULL,
  `Tipo` VARCHAR(25) NOT NULL,
  `Marca` VARCHAR(25) NOT NULL,
  `Cor` VARCHAR(25) NOT NULL,
  `Ano` INT NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `desafio_oficina`.`ordem_servico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `desafio_oficina`.`ordem_servico` ;

CREATE TABLE IF NOT EXISTS `desafio_oficina`.`ordem_servico` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `veiculo_ID` INT NOT NULL,
  `Data` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `DataEntrega` TIMESTAMP NOT NULL,
  `Autorizacao` CHAR(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`, `veiculo_ID`),
  CONSTRAINT `fk_ordem_servico_veiculo1`
    FOREIGN KEY (`veiculo_ID`)
    REFERENCES `desafio_oficina`.`veiculo` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `desafio_oficina`.`mao_de_obra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `desafio_oficina`.`mao_de_obra` ;

CREATE TABLE IF NOT EXISTS `desafio_oficina`.`mao_de_obra` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(255) NOT NULL,
  `valor` FLOAT NOT NULL,
  `Observacao` VARCHAR(255) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `desafio_oficina`.`cliente_has_veiculo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `desafio_oficina`.`cliente_veiculos` ;

CREATE TABLE IF NOT EXISTS `desafio_oficina`.`cliente_veiculos` (
  `cliente_ID` INT NOT NULL,
  `veiculo_ID` INT NOT NULL,
  `observacao` VARCHAR(255) NULL,
  PRIMARY KEY (`cliente_ID`, `veiculo_ID`),
  INDEX `fk_cliente_has_veiculo_veiculo1_idx` (`veiculo_ID` ASC) VISIBLE,
  INDEX `fk_cliente_has_veiculo_cliente_idx` (`cliente_ID` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_has_veiculo_cliente`
    FOREIGN KEY (`cliente_ID`)
    REFERENCES `desafio_oficina`.`cliente` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_has_veiculo_veiculo1`
    FOREIGN KEY (`veiculo_ID`)
    REFERENCES `desafio_oficina`.`veiculo` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `desafio_oficina`.`empregado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `desafio_oficina`.`empregado` ;

CREATE TABLE IF NOT EXISTS `desafio_oficina`.`empregado` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `oficina_ID` INT NOT NULL,
  `tipo` ENUM("Operacional", "Administrativo") NOT NULL DEFAULT 'Operacional',
  `rg` VARCHAR(10) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `endereco` VARCHAR(255) NULL,
  `salario` FLOAT NOT NULL,
  PRIMARY KEY (`ID`, `oficina_ID`),
  INDEX `fk_empregado_oficina1_idx` (`oficina_ID` ASC) VISIBLE,
  UNIQUE INDEX `rg_UNIQUE` (`rg` ASC) VISIBLE,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  CONSTRAINT `fk_empregado_oficina1`
    FOREIGN KEY (`oficina_ID`)
    REFERENCES `desafio_oficina`.`oficina` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `desafio_oficina`.`especialidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `desafio_oficina`.`especialidade` ;

CREATE TABLE IF NOT EXISTS `desafio_oficina`.`especialidade` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `desafio_oficina`.`especialidade_empregado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `desafio_oficina`.`especialidade_empregado` ;

CREATE TABLE IF NOT EXISTS `desafio_oficina`.`especialidade_empregado` (
  `especialidade_ID` INT NOT NULL,
  `empregado_ID` INT NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`especialidade_ID`, `empregado_ID`),
  INDEX `fk_especialidade_has_empregado_empregado1_idx` (`empregado_ID` ASC) VISIBLE,
  INDEX `fk_especialidade_has_empregado_especialidade1_idx` (`especialidade_ID` ASC) VISIBLE,
  CONSTRAINT `fk_especialidade_has_empregado_especialidade1`
    FOREIGN KEY (`especialidade_ID`)
    REFERENCES `desafio_oficina`.`especialidade` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_especialidade_has_empregado_empregado1`
    FOREIGN KEY (`empregado_ID`)
    REFERENCES `desafio_oficina`.`empregado` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `desafio_oficina`.`mo_os`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `desafio_oficina`.`mo_os` ;

CREATE TABLE IF NOT EXISTS `desafio_oficina`.`mo_os` (
  `mao_de_obra_ID` INT NOT NULL,
  `ordem_servico_ID` INT NOT NULL,
  `empregado_ID` INT NOT NULL COMMENT 'Empregado responsável pelo serviço',
  `unidade` DECIMAL NOT NULL COMMENT 'Informar a quantidade de horas utilizadas para realizar um determinado serviço',
  `obs` VARCHAR(255) NULL,
  PRIMARY KEY (`mao_de_obra_ID`, `ordem_servico_ID`, `empregado_ID`),
  INDEX `fk_mo_os_empregado1_idx` (`empregado_ID` ASC) VISIBLE,
  INDEX `fk_mo_os_mao_de_obra1_idx` (`mao_de_obra_ID` ASC) VISIBLE,
  INDEX `fk_mo_os_ordem_servico1_idx` (`ordem_servico_ID` ASC) VISIBLE,
  CONSTRAINT `fk_mo_os_empregado1`
    FOREIGN KEY (`empregado_ID`)
    REFERENCES `desafio_oficina`.`empregado` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mo_os_mao_de_obra1`
    FOREIGN KEY (`mao_de_obra_ID`)
    REFERENCES `desafio_oficina`.`mao_de_obra` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mo_os_ordem_servico1`
    FOREIGN KEY (`ordem_servico_ID`)
    REFERENCES `desafio_oficina`.`ordem_servico` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `desafio_oficina`.`equipe_empregados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `desafio_oficina`.`equipe_empregados` ;

CREATE TABLE IF NOT EXISTS `desafio_oficina`.`equipe_empregados` (
  `equipe_ID` INT NOT NULL,
  `empregado_ID` INT NOT NULL,
  PRIMARY KEY (`equipe_ID`, `empregado_ID`),
  INDEX `fk_equipe_has_empregado_empregado1_idx` (`empregado_ID` ASC) VISIBLE,
  INDEX `fk_equipe_has_empregado_equipe1_idx` (`equipe_ID` ASC) VISIBLE,
  CONSTRAINT `fk_equipe_has_empregado_equipe1`
    FOREIGN KEY (`equipe_ID`)
    REFERENCES `desafio_oficina`.`equipe` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_equipe_has_empregado_empregado1`
    FOREIGN KEY (`empregado_ID`)
    REFERENCES `desafio_oficina`.`empregado` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `desafio_oficina`.`peca_reposicao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `desafio_oficina`.`peca_reposicao` ;

CREATE TABLE IF NOT EXISTS `desafio_oficina`.`peca_reposicao` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(45) NOT NULL COMMENT 'código da peça',
  `descricao` VARCHAR(255) NOT NULL,
  `valor` FLOAT NOT NULL COMMENT 'valor da peça',
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `desafio_oficina`.`os_pecas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `desafio_oficina`.`os_pecas` ;

CREATE TABLE IF NOT EXISTS `desafio_oficina`.`os_pecas` (
  `peca_reposicao_ID` INT NOT NULL,
  `ordem_servico_ID` INT NOT NULL,
  `quantidade` INT NOT NULL,
  PRIMARY KEY (`peca_reposicao_ID`, `ordem_servico_ID`),
  INDEX `fk_peca_reposicao_has_ordem_servico_ordem_servico1_idx` (`ordem_servico_ID` ASC) VISIBLE,
  INDEX `fk_peca_reposicao_has_ordem_servico_peca_reposicao1_idx` (`peca_reposicao_ID` ASC) VISIBLE,
  CONSTRAINT `fk_peca_reposicao_has_ordem_servico_peca_reposicao1`
    FOREIGN KEY (`peca_reposicao_ID`)
    REFERENCES `desafio_oficina`.`peca_reposicao` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_peca_reposicao_has_ordem_servico_ordem_servico1`
    FOREIGN KEY (`ordem_servico_ID`)
    REFERENCES `desafio_oficina`.`ordem_servico` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `desafio_oficina`.`fornecedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `desafio_oficina`.`fornecedor` ;

CREATE TABLE IF NOT EXISTS `desafio_oficina`.`fornecedor` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `razao_social` VARCHAR(255) NOT NULL,
  `cnpj` CHAR(14) NOT NULL,
  `endereco` VARCHAR(255) NOT NULL,
  `telefone` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `desafio_oficina`.`fornecedor_pecas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `desafio_oficina`.`fornecedor_pecas` ;

CREATE TABLE IF NOT EXISTS `desafio_oficina`.`fornecedor_pecas` (
  `fornecedor_ID` INT NOT NULL,
  `peca_reposicao_ID` INT NOT NULL,
  `valor` FLOAT NULL,
  PRIMARY KEY (`fornecedor_ID`, `peca_reposicao_ID`),
  INDEX `fk_fornecedor_has_peca_reposicao_peca_reposicao1_idx` (`peca_reposicao_ID` ASC) VISIBLE,
  INDEX `fk_fornecedor_has_peca_reposicao_fornecedor1_idx` (`fornecedor_ID` ASC) VISIBLE,
  CONSTRAINT `fk_fornecedor_has_peca_reposicao_fornecedor1`
    FOREIGN KEY (`fornecedor_ID`)
    REFERENCES `desafio_oficina`.`fornecedor` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fornecedor_has_peca_reposicao_peca_reposicao1`
    FOREIGN KEY (`peca_reposicao_ID`)
    REFERENCES `desafio_oficina`.`peca_reposicao` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
